---
title: "01 R6 Simulation"
output: html_notebook
---

```{r}
library(conflicted)
library(raster)
library(tidyverse)
library(sf)
library(lubridate)
library(spatialEco)
library(ambient)
library(ggnewscale)
library(patchwork)
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")

R.files = list.files("../R", full.names = T)
for (f in R.files) source(f)
set.seed(1)
```

# Initialisation

```{r}
len_environment = 100
n_locations = 500
n_humans = 500
locations = tibble(
  X = runif(n_locations, min=0, max=len_environment),
  Y = runif(n_locations, min=0, max=len_environment)
)
humans = tibble(
  ID = seq_len(n_humans),
  # Start time of their current infection
  t_infection = ifelse(as.integer(runif(n_humans) < 0.1), 0, NA),
  # <Inf if person has one scheduled relapse
  t_relapse = Inf,
  # Probability of having enough gametocytes to infect a biting mosquito
  p_blood_gametocyte = 0,
  location_ix = replicate(n_humans, unique(sample(seq_len(n_locations), 2, T)), simplify=F),
  location_proportions = lapply(location_ix, function(x) {
    unnormed = sort(runif(length(x)), decreasing = TRUE)
    unnormed / sum(unnormed)
  })
)

mosquito_raster = make_perlin_mosquitoes(c(len_environment, len_environment))
mosquito_raster[][mosquito_raster[] < 3000] = 0

mysim = Simulation$new(humans = humans,
                       locations = locations,
                       mosquito_raster = mosquito_raster,
                       duration_human_infectivity = 60,
                       bite_rate = 0.1,
                       mosquito_death_rate = 0.25)

mysim$plot_mosquito_infectivity()
mysim$plot_human_infectivity()
mysim$plot_mosquito_migration()
mysim$plot_human_relapse()
mysim$plot_init()
```

Time step

```{r}
n_iter = 50
pb = txtProgressBar(min = 0, max = n_iter * 3, style = 3)
tictoc::tic(paste("Processing", n_iter, "iterations"))
# Run outbreak
for (t in seq_len(n_iter))  {
  setTxtProgressBar(pb, t)
  mysim$iterate(1)
}

# Interrupt and clear all current humand and mosquito infections
mysim$humans = mysim$humans %>%
  mutate(t_infection = NA)
mysim$mosquito_infections = mysim$mosquito_infections %>%
  slice(0)

# Run for more iterations
for (t in seq_len(n_iter*2))  {
  setTxtProgressBar(pb, t + n_iter)
  mysim$iterate(1)
}

tictoc::toc()

mysim$plot()
```


