---
title: "02 Construct Population"
output: html_notebook
---

Construct a synthetic population and write to a data file.

```{r}
library(conflicted)
library(raster)
library(tidyverse)
library(sf)
library(lubridate)
library(spatialEco)
library(ambient)
library(ggnewscale)
library(patchwork)
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")

R.files = list.files("../R", full.names = T)
for (f in R.files) source(f)
```

Construct a system of two villages where 200 people live in #1 and 100 live in #2. 10# of people spend half their time with another village.

```{r}
set.seed(1)
pop_1 = 200
pop_2 = 100
n_houses_1 = 30
n_houses_2 = 15
# Construct living locations
houses_1 = tibble(X = rnorm(n_houses_1, 0, 15),
                  Y = rnorm(n_houses_1, 0, 15)) %>%
  mutate(ID = row_number())
houses_2 = tibble(X = rnorm(n_houses_2, 100, 10),
                  Y = rnorm(n_houses_2, 0, 10)) %>%
  mutate(ID = row_number() + max(houses_1$ID))
houses = bind_rows(houses_1, houses_2)
loc_ix_1 = as.list(sample(houses_1$ID, pop_1, T))
for (i in 1:round(pop_1/10)) {
  loc_ix_1[[i]] = c(loc_ix_1[[i]], sample(houses_2$ID, 1))
}
loc_ix_2 = as.list(sample(houses_2$ID, pop_2, T))
for (i in 1:round(pop_2/10)) {
  loc_ix_2[[i]] = c(loc_ix_2[[i]], sample(houses_1$ID, 1))
}
location_ix = c(loc_ix_1, loc_ix_2)

# Construct people
people_1 = tibble(location_ix = loc_ix_1,
                  t_infection = NA_real_)
people_2 = tibble(location_ix = loc_ix_2,
                  t_infection = 0)
people = bind_rows(people_1, people_2) %>%
  mutate(ID = row_number(),
         t_relapse = Inf,
         p_blood_gametocyte = 0,
         location_proportions = lapply(location_ix, function(x) {
           unnormed = sort(runif(length(x)), decreasing = TRUE)
           unnormed / sum(unnormed)
         }))

# Construct mosquito environment
len_x = ceiling(max(houses$X)) - floor(min(houses$X))
len_y = ceiling(max(houses$Y)) - floor(min(houses$Y))
mosquito_raster = make_perlin_mosquitoes(list(xmin = floor(min(houses$X)),
                                              xmax = ceiling(max(houses$X)),
                                              ymin = floor(min(houses$Y)),
                                              ymax = ceiling(max(houses$Y))))
mosquito_raster[][mosquito_raster[] < 3000] = 0

villagesim = Simulation$new(humans = people,
                            locations = houses,
                            mosquito_raster = mosquito_raster,
                            duration_human_infectivity = 60,
                            bite_rate = 0.1,
                            mosquito_death_rate = 0.25)

villagesim$plot_mosquito_infectivity()
villagesim$plot_human_infectivity()
villagesim$plot_mosquito_migration()
villagesim$plot_human_relapse()
villagesim$plot_init()
```

```{r}
n_iter = 50
pb = txtProgressBar(min = 0, max = n_iter * 3, style = 3)
tictoc::tic(paste("Processing", n_iter, "iterations"))
# Run outbreak
for (t in seq_len(n_iter))  {
  setTxtProgressBar(pb, t)
  villagesim$iterate(1)
}

# Interrupt and clear all current humand and mosquito infections
villagesim$humans = villagesim$humans %>%
  mutate(t_infection = NA)
villagesim$mosquito_infections = villagesim$mosquito_infections %>%
  slice(0)

# Run for more iterations
for (t in seq_len(n_iter*2))  {
  setTxtProgressBar(pb, t + n_iter)
  villagesim$iterate(1)
}

tictoc::toc()

villagesim$plot()
```
