---
title: "03 Test Infection"
output: html_notebook
---

Verify that two people living in close proximity with lots of mosquitoes can be infected by each other.

```{r}
library(conflicted)
library(raster)
library(tidyverse)
library(sf)
library(lubridate)
library(spatialEco)
library(ambient)
library(ggnewscale)
library(patchwork)
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")

R.files = list.files("../R", full.names = T)
for (f in R.files) source(f)
```

```{r}
set.seed(0)
houses = tibble(X = c(0.4, 0.6), Y = 0.5)
people = tibble(
  ID = 1:2,
  location_ix = list(1,2),
  location_proportions = list(1, 1),
  t_infection = c(0, NA)
)

# Construct mosquito environment
mosquito_raster = raster(
  vals = 99999,
  ncols = 1,
  nrows = 1,
  xmn = 0,
  xmx = 1,
  ymn = 0,
  ymx = 1)

sim = Simulation$new(humans = people,
                            locations = houses,
                            mosquito_raster = mosquito_raster,
                            duration_human_infectivity = 60,
                            bite_rate = 99999,
                            mosquito_death_rate = 0.25)

plot_init(sim)
```

```{r}
for (i in 1:30) sim$iterate(1)
```

# Verification tests

```{r}
# At least one new person has been infected
testthat::expect_equal(sum(sim$history_infections$t_infection > 0) > 0, TRUE)
# At least one person's source is Transmission
testthat::expect_equal("Transmission" %in% sim$history_infections$source, TRUE)
plot(sim)
```
