---
title: "Animation Example"
output:
  rmarkdown::html_document:
    fig_width: 10
vignette: >
  %\VignetteIndexEntry{Animation Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(GeoMalaria)
library(dplyr)
library(tidyr)
library(progress)
library(ggplot2)
library(tictoc)
```

Construct a system of two villages where 200 people live in #1 and 100 live in #2. 10% of people in village 2 also spend half their time in village 1.

```{r}
set.seed(1)
pop_1 = 200
pop_2 = 100
n_houses_1 = 100 
n_houses_2 = 50
# Construct living locations
houses_1 = tibble(x = rnorm(n_houses_1, 0, 15),
                  y = rnorm(n_houses_1, 0, 15)) %>%
  mutate(ID = row_number())
houses_2 = tibble(x = rnorm(n_houses_2, 100, 10),
                  y = rnorm(n_houses_2, 0, 10)) %>%
  mutate(ID = row_number() + max(houses_1$ID))
houses = bind_rows(houses_1, houses_2)
loc_ix_1 = as.list(sample(houses_1$ID, pop_1, T))
loc_ix_2 = as.list(sample(houses_2$ID, pop_2, T))
# 10% of people in village 2 spend 50% of time in village 1
for (i in 1:round(pop_2 * 0.1)) {
  loc_ix_2[[i]] = c(loc_ix_2[[i]], sample(houses_1$ID, 1))
}
location_ix = c(loc_ix_1, loc_ix_2)

# Construct people
people_1 = tibble(location_ix = loc_ix_1,
                  t_infection = NA_real_)
people_2 = tibble(location_ix = loc_ix_2,
                  t_infection = 0)
people = bind_rows(people_1, people_2) %>%
  mutate(ID = row_number(),
         location_proportions = lapply(location_ix, function(x) {
           unnormed = rep(1, )
           rep(1/length(x), length(x))
         }))

# Construct mosquito environment
mosquito_raster = make_perlin_mosquitoes(list(xmin = floor(min(houses$x)),
                                              xmax = ceiling(max(houses$x)),
                                              ymin = floor(min(houses$y)),
                                              ymax = ceiling(max(houses$y))))
mosquito_raster[][mosquito_raster[] < 2000] = 0

sim = Simulation$new(population = people,
                     locations = houses,
                     mosquito_raster = mosquito_raster,
                     p_relapse = 0.2,
                     log_options = c("linelist", "EIR"))
plot(sim, init=TRUE)
```

# Run simulation

```{r}
# Begin outbreak
intervals = c(rep(1, 99))
pb = progress_bar$new(total = length(intervals),
                      format = "Simulating [:bar] :current/:total eta: :eta")
tictoc::tic()
for (i in seq_along(intervals))  {
  pb$tick()
  sim$iterate(intervals[i])
}
tictoc::toc()
```

# Render animation

Only do this on my computer because it's not important for vignettes or testing.

```{r}
if (interactive()) {
  tictoc::tic()
  plot_anim(sim, file="animation.mp4", verbose=TRUE)
  tictoc::toc()
}
```

```{r, eval=FALSE}
# Experiment with parallelisation
library(parallel)
library(doParallel)
library(foreach)
my.cluster <- parallel::makeCluster(
  1, 
  type = "FORK"
)
registerDoParallel(cl = my.cluster)
foreach(
  i = 1:10, 
  .combine = 'c'
) %dopar% {
    sqrt(i)
}
stopCluster(my.cluster)
```

