---
title: "Clinical Outcomes"
output:
  rmarkdown::html_document:
    fig_width: 10
vignette: >
  %\VignetteIndexEntry{Clinical Outcomes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(GeoMalaria)
library(dplyr)
```

Construct a system of two villages where 200 people live in #1 and 100 live in #2. 10% of people in village 2 also spend half their time in village 1.

```{r}
set.seed(0)
n = 200
n_infected = ceiling(n/10)
n_houses = 30
# Construct living locations
houses = tibble(x = rnorm(n_houses, 0, 15),
                y = rnorm(n_houses, 0, 15)) %>%
  mutate(ID = row_number())
loc_ix = as.list(sample(houses$ID, n, T))

# Construct people
population = tibble(location_ix = loc_ix,
                    t_infection = sample(c(rep(0, n_infected), rep(NA, n-n_infected)), n)) %>%
  mutate(ID = row_number(),
         location_proportions = lapply(location_ix, function(x) {
           unnormed = rep(1, )
           rep(1/length(x), length(x))
         }))

# Construct mosquito environment
mosquito_raster = make_perlin_mosquitoes(list(xmin = floor(min(houses$x)),
                                              xmax = ceiling(max(houses$x)),
                                              ymin = floor(min(houses$y)),
                                              ymax = ceiling(max(houses$y))))
mosquito_raster[][mosquito_raster[] < 3000] = 0

mos = Mosquito$new()
human = Human$new()
sim = Simulation$new(population = population,
                     locations = houses,
                     mosquito = mos,
                     human = human,
                     mosquito_raster = mosquito_raster,
                     p_relapse = 0.2)


plot(mos)
plot(human)
plot(sim)
```

# Run simulation

```{r}
# Begin outbreak
for (t in seq_len(50))  {
  villagesim$iterate(1)
}

# Interrupt and clear all current human and mosquito infections
villagesim$population = villagesim$population %>%
  mutate(t_infection = NA)
villagesim$mosquito_infections = villagesim$mosquito_infections %>%
  slice(0)

# Run for more iterations
for (t in seq_len(150))  {
  villagesim$iterate(1)
}

plot(villagesim) +
  geom_vline(xintercept = 50, linetype="dashed") +
  annotate("text", x=50, y=1, angle=90, hjust=0, vjust=-0.2, label="MDA")

ggsave("mda_fail.png", width=1920, height=1080, units="px", dpi=150)
```
