library(R6)

Simulation = R6Class(
  "Simulation",
  public = list(
    # Constants
    t = 0,
    mosquito_raster = NULL,
    n_people = NULL,
    max_mosquito_lifespan = 0,
    max_human_infectivity = NULL,
    max_mosquito_flight_range = NULL,
    bite_rate = NULL,
    mosquito_death_rate = NULL,
    sporozoite_infection_rate = 0.75,
    
    # States
    people = NULL,
    mosquito_infections = tibble(t_inoculation = NA_real_),
    people_infections = tibble(),
    
    #' Initialize a simulation instance
    #' 
    #' @param people dataframe of residents in the area
    #' @param mosquito_raster raster of the number of mosquitoes per cell
    #' @param max_human_infectivity maximum infectious period of a humamn in days
    #' @param mosquito_death_rate proportion of mosquitoes that die per day
    #' @param bite_rate probability of each mosquito biting a humanin a cell
    initialize = function(people,
                          mosquito_raster,
                          max_human_infectivity, # days
                          mosquito_death_rate, # per day
                          bite_rate) {
      
      # Raster for fine visualisation of continuous fields
      bounds = extent(mosquito_raster)
      private$vis_raster = raster(vals=0, nrows=100, ncols=100,
                                  xmn=bounds@xmin, xmx=bounds@xmax,
                                  ymn=bounds@ymin, ymx=bounds@ymax, 
                                  crs="+units=km")
      
      # Parameters
      self$people = people
      self$mosquito_raster = mosquito_raster
      self$max_human_infectivity = max_human_infectivity
      self$bite_rate = bite_rate
      self$mosquito_death_rate = mosquito_death_rate
      
      # Calculate reasonable mosquito bounds
      # capture the vast majority of the mosquito lifespan
      while (private$mosquito_survival(self$max_mosquito_lifespan) > 0.01) {
        self$max_mosquito_lifespan = self$max_mosquito_lifespan + 1
      }
      # Capture 95% of the distance travelled at the max lifespan
      self$max_mosquito_flight_range = qnorm(0.975, sd=sqrt(private$mosquito_travel * self$max_mosquito_lifespan))
    },
    
    
    plot_init = function() {
      mosquito_data = as.data.frame(self$mosquito_raster, xy=T) %>%
        rename(X = x, Y = y)
      humans = self$people %>%
        mutate(Infection = case_when(t_infection == self$t ~ "Importation",
                                     TRUE ~ "None"))
      ggplot(mapping = aes(x=X, y=Y)) +
        geom_raster(data = mosquito_data, aes(fill=count)) +
        geom_point(data = humans, aes(color=Infection)) +
        coord_equal() +
        scale_fill_viridis_c(option = "magma") +
        scale_color_manual(values = c("Importation"="tomato",
                                      "None"="white")) +
        labs(fill = "Mos/km^2")
    },
    
    
    iterate = function(dt, debug=FALSE) {
      self$t = self$t + dt
      
      # Calculate current state of human infectivity
      self$people$blood_gametocyte_prob = private$human_infectivity(self$t - self$people$t_infection)
      
      # Expose mosquitos and add to current infected mosquitos
      new_mosquito_infections = self$people %>%
        filter(blood_gametocyte_prob > 0) %>%
        select(-ID, -infected, t_infection) %>%
        # Infect mosquitos at rate (assume no susc. depletion)
        # Number of new infected mosquitoes generated by this person
        mutate(infected_count = blood_gametocyte_prob *
                 self$bite_rate *
                 my_extract(self$mosquito_raster, .[c("X", "Y")]) * # local density
                 dt,
               t_inoculation = self$t) %>%
        filter(infected_count > 0) %>%
        select(X, Y, infected_count, t_inoculation)
      
      # Add new events to existing events
      self$mosquito_infections = self$mosquito_infections %>%
        # Remove expired events
        filter(self$t - t_inoculation < self$max_mosquito_lifespan) %>%
        bind_rows(new_mosquito_infections) %>%
        # Calculate current infectivity of infected mosquito clouds integrated over space   # Number of live mosquitoes with mature sporozoites from this event
        mutate(infectious_count = infected_count *
                 private$mosquito_survival(self$t - t_inoculation) *
                 private$mosquito_sporogony(self$t - t_inoculation))
      
      # Expose and infect people
      susceptible = mysim$people %>% filter(!infected)
      susceptible_EIR = apply(
        susceptible,
        1,
        function(person) {
          bites = mysim$mosquito_infections %>%
            mutate(distance = sqrt((X - person["X"])^2 + (Y - person["Y"])^2),
                   ento_inoculation_rate = infectious_count *
                     self$bite_rate *
                     # Disperse load over total cloud area (TODO: check integral=1)
                     private$mosquito_migration(distance, self$t-t_inoculation) *
                     self$sporozoite_infection_rate) # EIR = HBR * SIR
          sum(bites$ento_inoculation_rate)
        }
      )
      # shortcut for P(x) > 0, x ~Pois(EIR*dt)
      infect_IDs = susceptible$ID[runif(nrow(susceptible)) > exp(-susceptible_EIR * dt)]
      
      # Update population
      self$people$infected[infect_IDs] = TRUE
      self$people$t_infection[infect_IDs] = self$t
      
      invisible(infect_IDs)
    },
    
    plot = function() {
      p1 = self$plot_state()
      p2 = self$plot_epicurve()
      p1 / p2 + plot_layout(heights = c(4, 1), guides = "collect")
    },
    
    plot_state = function() {
      humans = self$people %>%
        mutate(Infection = case_when(t_infection == self$t ~ "New",
                                     t_infection < self$t ~ "Historical",
                                     TRUE ~ "None"))
      
      vis_grid = as.data.frame(private$vis_raster, xy=T) %>%
        rename(X = x, Y = y)
      vis_grid$ento_inoculation_rate = apply(
        vis_grid,
        1,
        function(point) {
          bites = mysim$mosquito_infections %>%
            mutate(distance = sqrt((X - point["X"])^2 + (Y - point["Y"])^2),
                   ento_inoculation_rate = infectious_count *
                     # Disperse load over total cloud area (TODO: check integral=1)
                     private$mosquito_migration(distance, self$t-t_inoculation) *
                     self$bite_rate *
                     self$sporozoite_infection_rate) # EIR = HBR * SIR
          sum(bites$ento_inoculation_rate)
        }
      )
      
      ggplot(vis_grid, aes(x=X, y=Y)) +
        geom_raster(aes(fill=ento_inoculation_rate), interpolate=TRUE) +
        scale_fill_viridis_c(option="inferno", limits=c(0, NA)) +
        labs(fill = "EIR") +
        new_scale("fill") +
        geom_point(aes(fill=blood_gametocyte_prob, color=Infection), data=humans, pch=21, size=2, stroke=1.5) +
        labs(fill = "Gametocyte\nprobability") +
        scale_fill_viridis_c(limits=c(0, 1)) +
        scale_color_manual(values=c("New"="tomato",
                                    "Historical"="steelblue",
                                    "None"=NA)) +
        coord_equal() +
        labs(title = paste("t =", self$t), x = NULL, y = NULL) +
        theme_minimal() +
        theme(legend.key.height = unit(10, "pt"),
              axis.text = element_blank(),
              axis.ticks = element_blank(),
              panel.background = element_blank(),
              panel.grid = element_blank())
    },
    
    plot_epicurve = function() {
      self$people %>%
        filter(t_infection > 0) %>%
        ggplot(aes(x = t_infection)) +
        geom_bar(width = 0.9) +
        coord_cartesian(xlim = c(0, NA)) +
        labs(x = "Infection time",
             y = NULL) +
        theme_minimal() +
        theme(panel.grid.minor = element_blank())
    },
    
    #' Plot spread of mosquitoes over distance
    plot_mosquito_migration = function() {
      DX = seq(-1.1 * self$max_mosquito_flight_range,
               1.1 * self$max_mosquito_flight_range,
               length.out = 100)
      DT = seq(1, self$max_mosquito_lifespan, length.out=7)
      DXDT = expand.grid(dx=DX, dt=DT) %>%
        mutate(density = private$mosquito_migration(dx, dt))
      with(DXDT, qplot(dx, density, color=dt, group=dt, geom="line") +
             geom_vline(xintercept=c(-1,1) * self$max_mosquito_flight_range) +
             scale_color_continuous(breaks = DT) +
             labs(x = "Distance", color = "Days since\nblood meal")
      )
    },
    
    
    plot_mosquito_infectivity = function() {
      tibble(dt = seq(0, self$max_mosquito_lifespan, length.out=1000),
             survival = private$mosquito_survival(dt),
             sporozoites = private$mosquito_sporogony(dt),
             infectivity = survival*sporozoites) %>%
        pivot_longer(cols = -dt) %>%
        ggplot(aes(x = dt, y = value, color = name, linetype = name)) +
        geom_line() +
        labs(x = "Days since blood meal", y = "Probability")
    },
    
    plot_human_infectivity = function() {
      tibble(dt = seq(0, self$max_human_infectivity, length.out=1000),
             gametocyte_load = private$human_infectivity(dt)) %>%
        ggplot(aes(x = dt, y = gametocyte_load)) +
        geom_line() +
        labs(title = "Probability of inoculating a biting mosquito",
             x = "Days since infection", y = "Probability")
    }
  ),
  
  
  
  private = list(
    env_raster = NULL,
    vis_raster = NULL,
    
    #' Proportion of mosquitoes that survive over time
    mosquito_survival = function(dt) {
      survival = dexp(dt, rate=self$mosquito_death_rate) / self$mosquito_death_rate
    },
    
    #' Proportion of mosquitoes with sporozoites over time
    mosquito_sporogony = function(dt) {
      approx(c(8, 10), c(0, 1), dt, yleft=0, yright=1)$y
    },
    
    # 1-D variance of mosquito travel in (km/day)^2
    mosquito_travel = 1^2,
    mosquito_migration = function(dx, dt) {
      dnorm(dx, sd=sqrt(private$mosquito_travel * dt))
    },
    
    #' Lifecycle stages for P. vivax in humans after inoculation
    #'
    #' @param t days since inoculation
    #' 
    #' @return vector of probability of infecting mosquito with gametocytes in the grid cell
    human_infectivity = function(dt) {
      infectivity = approx(c(12, 17, 20, self$max_human_infectivity),
                           c(0, 1, 1, 0),
                           dt,
                           yleft = 0, yright = 0)$y
      replace_na(infectivity, 0)
    }
  )
)
